"""initial schema

Revision ID: 46601b36ed37
Revises:
Create Date: 2026-09-24 12:59:49.735832

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46601b36ed37"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "levels",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_levels")),
        sa.UniqueConstraint("rank", name=op.f("uq_levels_rank")),
    )
    op.create_table(
        "skills",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_skills")),
    )
    op.create_table(
        "stimuli",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("text", "audio", name="stimuluskind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("audio_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stimuli")),
        sa.UniqueConstraint("code", name=op.f("uq_stimuli_code")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column(
            "role",
            sa.Enum("student", "teacher", "admin", name="role", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "assessments",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("level_code", sa.String(length=16), nullable=True),
        sa.Column("time_limit_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("max_attempts", sa.SmallInteger(), nullable=True),
        sa.Column("cooldown_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("shuffle_questions", sa.Boolean(), nullable=False),
        sa.Column("shuffle_options", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["level_code"], ["levels.code"], name=op.f("fk_assessments_level_code_levels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
        sa.UniqueConstraint("slug", name=op.f("uq_assessments_slug")),
    )
    op.create_table(
        "questions",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "multiple_choice",
                "fill_blank",
                "comprehension",
                "vocabulary",
                name="questiontype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "response_format",
            sa.Enum("choice", "text", name="responseformat", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("skill_code", sa.String(length=32), nullable=False),
        sa.Column("level_code", sa.String(length=16), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer_key", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("stimulus_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["level_code"], ["levels.code"], name=op.f("fk_questions_level_code_levels")
        ),
        sa.ForeignKeyConstraint(
            ["skill_code"], ["skills.code"], name=op.f("fk_questions_skill_code_skills")
        ),
        sa.ForeignKeyConstraint(
            ["stimulus_id"], ["stimuli.id"], name=op.f("fk_questions_stimulus_id_stimuli")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("code", name=op.f("uq_questions_code")),
    )
    op.create_index(op.f("ix_questions_level_code"), "questions", ["level_code"], unique=False)
    op.create_index(op.f("ix_questions_skill_code"), "questions", ["skill_code"], unique=False)
    op.create_table(
        "assessment_questions",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("points", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_assessment_questions_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_assessment_questions_question_id_questions"),
        ),
        sa.PrimaryKeyConstraint(
            "assessment_id", "question_id", name=op.f("pk_assessment_questions")
        ),
    )
    op.create_table(
        "attempts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "submitted",
                "expired",
                name="attemptstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("layout", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("integrity_flags", sa.SmallInteger(), nullable=False),
        sa.Column("score_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("correct_count", sa.SmallInteger(), nullable=True),
        sa.Column("incorrect_count", sa.SmallInteger(), nullable=True),
        sa.Column("suggested_level_code", sa.String(length=16), nullable=True),
        sa.Column("skill_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ai_feedback", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_attempts_assessment_id_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["suggested_level_code"],
            ["levels.code"],
            name=op.f("fk_attempts_suggested_level_code_levels"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_attempts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
    )
    op.create_index(
        "ix_attempts_user_submitted", "attempts", ["user_id", "submitted_at"], unique=False
    )
    op.create_index(
        "uq_attempts_open_per_user",
        "attempts",
        ["user_id", "assessment_id"],
        unique=True,
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.create_table(
        "attempt_answers",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_attempt_answers_attempt_id_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("fk_attempt_answers_question_id_questions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_answers")),
        sa.UniqueConstraint(
            "attempt_id", "question_id", name=op.f("uq_attempt_answers_attempt_id")
        ),
    )
    op.create_index(
        op.f("ix_attempt_answers_attempt_id"), "attempt_answers", ["attempt_id"], unique=False
    )
    op.create_table(
        "attempt_events",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "tab_hidden",
                "window_blur",
                "paste",
                "copy",
                "fullscreen_exit",
                "resumed",
                name="integrityeventtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_attempt_events_attempt_id_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_events")),
    )
    op.create_index(
        op.f("ix_attempt_events_attempt_id"), "attempt_events", ["attempt_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attempt_events_attempt_id"), table_name="attempt_events")
    op.drop_table("attempt_events")
    op.drop_index(op.f("ix_attempt_answers_attempt_id"), table_name="attempt_answers")
    op.drop_table("attempt_answers")
    op.drop_index(
        "uq_attempts_open_per_user",
        table_name="attempts",
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.drop_index("ix_attempts_user_submitted", table_name="attempts")
    op.drop_table("attempts")
    op.drop_table("assessment_questions")
    op.drop_index(op.f("ix_questions_skill_code"), table_name="questions")
    op.drop_index(op.f("ix_questions_level_code"), table_name="questions")
    op.drop_table("questions")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("stimuli")
    op.drop_table("skills")
    op.drop_table("levels")
    # ### end Alembic commands ###
